const API = localStorage.getItem("apiBase") || "http://127.0.0.1:8000";
const $=id=>document.getElementById(id);
function token(){return localStorage.getItem("token")||""}
function logout(){localStorage.clear();location.href="index.html"}
async function api(path,opts={}){opts.headers={...(opts.headers||{}),"Content-Type":"application/json","Authorization":`Bearer ${token()}`};const r=await fetch(API+path,opts);const data=await r.json().catch(()=>({detail:"Server error"}));if(!r.ok)throw new Error(data.detail||"Request failed");return data}
if($("loginForm")){
 let role="customer";
 document.querySelectorAll(".role").forEach(b=>b.onclick=()=>{document.querySelectorAll(".role").forEach(x=>x.classList.remove("active"));b.classList.add("active");role=b.dataset.role;$("roleHint").textContent=role==="staff"?"Demo: staff / staff123":role==="developer"?"Demo: developer / dev123":"Customer: any username and password."});
 $("loginForm").onsubmit=async e=>{e.preventDefault();$("loginMsg").textContent="";try{const d=await api("/api/login",{method:"POST",body:JSON.stringify({username:$("username").value,password:$("password").value,role})});localStorage.setItem("token",d.token);localStorage.setItem("role",d.role);localStorage.setItem("username",d.username);location.href=role==="customer"?"customer.html":role==="staff"?"staff.html":"developer.html"}catch(x){$("loginMsg").textContent=x.message}}
}
if($("customerForm")){
 $("userLabel").textContent=localStorage.getItem("username")||"Customer";
 $("customerForm").onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target).entries());for(const k of ["person_age","person_income","person_emp_length","loan_amnt","loan_int_rate","loan_percent_income","cb_person_cred_hist_length","loan_tenure","existing_emi"])o[k]=Number(o[k]);o.customer_username=localStorage.getItem("username")||"customer";try{const d=await api("/api/applications/preview",{method:"POST",body:JSON.stringify(o)});$("recommendation").innerHTML=`<div class="eyebrow">RECOMMENDATIONS</div><h2>${d.recommended_loan}</h2><p class="muted">Products selected for this application.</p>${d.recommended_products.map(p=>`<div class="product">${p}</div>`).join("")}<button class="primary full" id="submitApp">Submit application</button>`;$("submitApp").onclick=async()=>{try{await api("/api/applications",{method:"POST",body:JSON.stringify(o)});$("customerMsg").textContent="Application submitted successfully.";$("customerMsg").style.color="var(--green)";$("submitApp").disabled=true}catch(x){$("customerMsg").textContent=x.message}}}catch(x){$("customerMsg").textContent=x.message}}
}
async function loadStaff(){if(!$("appsBody"))return;try{const apps=await api("/api/applications");const counts={total:apps.length,pending:apps.filter(x=>x.status==="Pending").length,approved:apps.filter(x=>x.status==="Approved").length,rejected:apps.filter(x=>x.status==="Rejected").length};$("stats").innerHTML=Object.entries(counts).map(([k,v])=>`<div class="stat"><div class="muted">${k}</div><strong>${v}</strong></div>`).join("");$("appsBody").innerHTML=apps.map(a=>`<tr><td><button class="row-btn" onclick='showApplication(${JSON.stringify(a)})'>${a.application_id}</button></td><td>${a.customer_username}</td><td>${Number(a.loan_amnt).toLocaleString()}</td><td class="${a.risk_level==="High"?"risk-high":"risk-low"}">${a.risk_level}</td><td>${a.default_probability===""?"—":(Number(a.default_probability)*100).toFixed(1)+"%"}</td><td>${a.status}</td></tr>`).join("")}catch(x){$("detail").innerHTML=`<p class="message">${x.message}</p>`}}
function showApplication(a){$("detail").innerHTML=`<div class="eyebrow">APPLICATION ${a.application_id}</div><h2>${a.customer_username}</h2><p>Loan: <b>${Number(a.loan_amnt).toLocaleString()}</b> · Purpose: <b>${a.loan_intent}</b> · Risk: <b>${a.risk_level}</b> · Default probability: <b>${a.default_probability===""?"—":(Number(a.default_probability)*100).toFixed(1)+"%"}</b></p><p>Recommended products: <b>${a.recommended_products}</b></p><div class="detail-actions"><button class="primary" onclick='decide("${a.application_id}","Approved")'>Approve</button><button class="primary danger" onclick='decide("${a.application_id}","Rejected")'>Reject</button></div>`}
async function decide(id,status){const product=status==="Approved"?prompt("Accepted product (optional):","")||"":"";try{await api("/api/applications/"+id,{method:"PATCH",body:JSON.stringify({staff_decision:status,accepted_product:product})});loadStaff()}catch(x){alert(x.message)}}
if($("appsBody"))loadStaff();
async function loadDeveloper(){if(!$("devStats"))return;try{const d=await api("/api/developer/metrics");$("devStats").innerHTML=[["Records",d.rows],["Default rate",(d.default_rate*100).toFixed(2)+"%"],["Avg loan","₹"+Math.round(d.avg_loan_amount).toLocaleString()],["Algorithm",d.algorithm]].map(x=>`<div class="stat"><div class="muted">${x[0]}</div><strong>${x[1]}</strong></div>`).join("");$("devModel").textContent=`${d.algorithm} · ${d.trees} trees · max depth ${d.max_depth}`}catch(x){$("devModel").textContent=x.message}}
if($("devStats"))loadDeveloper();
